#!/bin/bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Material-Black-Plum-3.38'
ICONS='oomox-Bluloco-dark'
FONT='Noto Sans 11'
CURSOR='Adwaita'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
